[supabase]
url = "https://jpezxmzlulouipntyfhs.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwZXp4bXpsdWxvdWlwbnR5ZmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMzc2OTQsImV4cCI6MjA5MjcxMzY5NH0.LBo_WtDCCct16RV6xeMo07cj-MEvqh1tgcFPjgvQquQ"